DROP TABLE IF EXISTS Acteur ;
CREATE TABLE Acteur (ID_Acteur INT AUTO_INCREMENT NOT NULL,
Nom_Acteur VARCHAR(255),
Prénom_Acteur VARCHAR(255),
Rôle_Acteur VARCHAR(255),
Date_de_naissance_Acteur VARCHAR(255),
PRIMARY KEY (ID_Acteur)) ENGINE=InnoDB;

DROP TABLE IF EXISTS Actrice ;
CREATE TABLE Actrice (ID_Actrice INT AUTO_INCREMENT NOT NULL,
Nom_Actrice VARCHAR(255),
Prénom_Actrice VARCHAR(255),
Rôle_Actrice VARCHAR(255),
Date_de_naissance_Actrice VARCHAR(255),
PRIMARY KEY (ID_Actrice)) ENGINE=InnoDB;

DROP TABLE IF EXISTS Admin ;
CREATE TABLE Admin (ID_Admin INT AUTO_INCREMENT NOT NULL,
PRIMARY KEY (ID_Admin)) ENGINE=InnoDB;

DROP TABLE IF EXISTS User ;
CREATE TABLE User (ID_User INT AUTO_INCREMENT NOT NULL,
Nom_User VARCHAR(255),
Prénom_User VARCHAR(255),
Email_User VARCHAR(255),
Mot_de_passe_User VARCHAR(255),
Rôle_User VARCHAR(255),
Films_préférés_User VARCHAR(255),
PRIMARY KEY (ID_User)) ENGINE=InnoDB;

DROP TABLE IF EXISTS Film ;
CREATE TABLE Film (ID_Film INT AUTO_INCREMENT NOT NULL,
Titre_Film VARCHAR(255),
Durée_Film VARCHAR(255),
Année_de_Sortie_Film VARCHAR(255),
PRIMARY KEY (ID_Film)) ENGINE=InnoDB;

DROP TABLE IF EXISTS Réalisateur ;
CREATE TABLE Réalisateur (ID_Réalisateur INT AUTO_INCREMENT NOT NULL,
Nom_Réalisateur VARCHAR(255),
Prénom_Réalisateur VARCHAR(255),
PRIMARY KEY (ID_Réalisateur)) ENGINE=InnoDB;

DROP TABLE IF EXISTS A_joué_dans ;
CREATE TABLE A_joué_dans (ID_Film **NOT FOUND** AUTO_INCREMENT NOT NULL,
ID_Acteur **NOT FOUND** NOT NULL,
ID_Actrice **NOT FOUND** NOT NULL,
PRIMARY KEY (ID_Film,
 ID_Acteur,
 ID_Actrice)) ENGINE=InnoDB;

DROP TABLE IF EXISTS A_réalisé ;
CREATE TABLE A_réalisé (ID_Réalisateur **NOT FOUND** AUTO_INCREMENT NOT NULL,
ID_Film **NOT FOUND** NOT NULL,
PRIMARY KEY (ID_Réalisateur,
 ID_Film)) ENGINE=InnoDB;

DROP TABLE IF EXISTS Aime ;
CREATE TABLE Aime (ID_User **NOT FOUND** AUTO_INCREMENT NOT NULL,
ID_Film **NOT FOUND** NOT NULL,
PRIMARY KEY (ID_User,
 ID_Film)) ENGINE=InnoDB;

DROP TABLE IF EXISTS Gère ;
CREATE TABLE Gère (ID_Admin **NOT FOUND** AUTO_INCREMENT NOT NULL,
ID_Actrice **NOT FOUND** NOT NULL,
ID_Acteur **NOT FOUND** NOT NULL,
ID_Réalisateur **NOT FOUND** NOT NULL,
ID_Film **NOT FOUND** NOT NULL,
PRIMARY KEY (ID_Admin,
 ID_Actrice,
 ID_Acteur,
 ID_Réalisateur,
 ID_Film)) ENGINE=InnoDB;

ALTER TABLE A_joué_dans ADD CONSTRAINT FK_A_joué_dans_ID_Film FOREIGN KEY (ID_Film) REFERENCES Film (ID_Film);

ALTER TABLE A_joué_dans ADD CONSTRAINT FK_A_joué_dans_ID_Acteur FOREIGN KEY (ID_Acteur) REFERENCES Acteur (ID_Acteur);
ALTER TABLE A_joué_dans ADD CONSTRAINT FK_A_joué_dans_ID_Actrice FOREIGN KEY (ID_Actrice) REFERENCES Actrice (ID_Actrice);
ALTER TABLE A_réalisé ADD CONSTRAINT FK_A_réalisé_ID_Réalisateur FOREIGN KEY (ID_Réalisateur) REFERENCES Réalisateur (ID_Réalisateur);
ALTER TABLE A_réalisé ADD CONSTRAINT FK_A_réalisé_ID_Film FOREIGN KEY (ID_Film) REFERENCES Film (ID_Film);
ALTER TABLE Aime ADD CONSTRAINT FK_Aime_ID_User FOREIGN KEY (ID_User) REFERENCES User (ID_User);
ALTER TABLE Aime ADD CONSTRAINT FK_Aime_ID_Film FOREIGN KEY (ID_Film) REFERENCES Film (ID_Film);
ALTER TABLE Gère ADD CONSTRAINT FK_Gère_ID_Admin FOREIGN KEY (ID_Admin) REFERENCES Admin (ID_Admin);
ALTER TABLE Gère ADD CONSTRAINT FK_Gère_ID_Actrice FOREIGN KEY (ID_Actrice) REFERENCES Actrice (ID_Actrice);
ALTER TABLE Gère ADD CONSTRAINT FK_Gère_ID_Acteur FOREIGN KEY (ID_Acteur) REFERENCES Acteur (ID_Acteur);
ALTER TABLE Gère ADD CONSTRAINT FK_Gère_ID_Réalisateur FOREIGN KEY (ID_Réalisateur) REFERENCES Réalisateur (ID_Réalisateur);
ALTER TABLE Gère ADD CONSTRAINT FK_Gère_ID_Film FOREIGN KEY (ID_Film) REFERENCES Film (ID_Film);
